"use strict";

const { SIGNAL_CONTRACT_VERSION, AGREEMENT_CONTRACT_VERSION } = require("./constants");
function round(value, places = 6) { return Number(Number(value).toFixed(places)); }
function quantile(values, position) { const sorted = [...values].sort((a, b) => a - b); const index = (sorted.length - 1) * position; const lower = Math.floor(index), upper = Math.ceil(index); return lower === upper ? sorted[lower] : sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower); }
function pathDrawdown(path) { let peak = path[0].close, worst = 0; for (const row of path) { peak = Math.max(peak, row.close); worst = Math.min(worst, row.close / peak - 1); } return worst; }
function pathVolatility(path) { if (path.length < 2) return 0; const returns = path.slice(1).map((row, index) => row.close / path[index].close - 1); const mean = returns.reduce((sum, value) => sum + value, 0) / returns.length; return Math.sqrt(returns.reduce((sum, value) => sum + (value - mean) ** 2, 0) / returns.length); }
function direction(value) { return value > 0 ? "bullish" : value < 0 ? "bearish" : "mixed"; }
function deriveSignal({ ticker, horizon, generatedAt, samples, inputLastClose, dataQuality }) {
  const terminalReturns = samples.map((path) => path.at(-1).close / inputLastClose - 1); const pathLength = samples[0].length;
  const medianPath = Array.from({ length: pathLength }, (_, index) => ({ timestamp: samples[0][index].timestamp, open: round(quantile(samples.map((path) => path[index].open), .5)), high: round(quantile(samples.map((path) => path[index].high), .5)), low: round(quantile(samples.map((path) => path[index].low), .5)), close: round(quantile(samples.map((path) => path[index].close), .5)), volume: round(quantile(samples.map((path) => path[index].volume), .5)) }));
  const lowerPath = samples[0].map((row, index) => ({ timestamp: row.timestamp, close: round(quantile(samples.map((path) => path[index].close), .1)) })); const upperPath = samples[0].map((row, index) => ({ timestamp: row.timestamp, close: round(quantile(samples.map((path) => path[index].close), .9)) })); const medianExpectedReturn = quantile(terminalReturns, .5);
  return { contractVersion: SIGNAL_CONTRACT_VERSION, ticker, generatedAt, horizon, direction: direction(medianExpectedReturn), positiveReturnShare: round(terminalReturns.filter((value) => value > 0).length / terminalReturns.length), medianExpectedReturn: round(medianExpectedReturn), lowerReturnBand: round(quantile(terminalReturns, .1)), upperReturnBand: round(quantile(terminalReturns, .9)), forecastVolatility: round(quantile(samples.map(pathVolatility), .5)), forecastMaxDrawdown: round(quantile(samples.map(pathDrawdown), .5)), pathStability: round(1 / (1 + Math.abs(quantile(terminalReturns, .9) - quantile(terminalReturns, .1)))), sampleCount: samples.length, dataQuality, modelStatus: "available", medianPath, lowerPath, upperPath, terminalReturns: terminalReturns.map((value) => round(value)) };
}
function agreement(legacyDirection, kronosDirection, legacyHorizon, kronosHorizon) { let state = "unavailable"; if (["bullish", "bearish"].includes(legacyDirection) && ["bullish", "bearish"].includes(kronosDirection)) state = legacyDirection === kronosDirection ? (legacyHorizon === kronosHorizon ? "aligned" : "partially_aligned") : "conflicting"; return { contractVersion: AGREEMENT_CONTRACT_VERSION, state, legacyDirection: legacyDirection || "unavailable", kronosDirection: kronosDirection || "unavailable", legacyHorizon: legacyHorizon || null, kronosMappedHorizon: kronosHorizon || null, productionInfluence: false }; }
module.exports = { quantile, pathDrawdown, pathVolatility, deriveSignal, agreement, direction };
