"use strict";

const FORECAST_CONTRACT_VERSION = "KRONOS_SHADOW_FORECAST_V1";
const SIGNAL_CONTRACT_VERSION = "KRONOS_SHADOW_SIGNAL_V1";
const OUTCOME_CONTRACT_VERSION = "KRONOS_SHADOW_OUTCOME_V1";
const AGREEMENT_CONTRACT_VERSION = "MODEL_AGREEMENT_V1";
const STORE_VERSION = 1;
const DEFAULT_MODEL = "NeoQuasar/Kronos-mini";
const DEFAULT_TOKENIZER = "NeoQuasar/Kronos-Tokenizer-2k";
const MAX_OBSERVATIONS = 512;
const MIN_OBSERVATIONS = 64;
const MAX_SAMPLES = 16;
const DEFAULT_SAMPLES = 8;
const MAX_FORECAST_BARS = 22;
const DEFAULT_TIMEOUT_MS = 20_000;
const MAX_QUEUE = 4;
const MAX_CONCURRENCY = 1;
const MAX_FORECASTS = 500;
const MAX_OUTCOMES = 500;
const MAX_RESPONSE_BYTES = 2 * 1024 * 1024;
const HORIZON_MAPPINGS = Object.freeze({
  "1-Day": Object.freeze({ bars: 1, label: "1 trading day" }),
  "7-Day": Object.freeze({ bars: 5, label: "5 future daily trading bars" }),
  "1-Month": Object.freeze({ bars: 22, label: "22 future daily trading bars" }),
});

module.exports = Object.freeze({ FORECAST_CONTRACT_VERSION, SIGNAL_CONTRACT_VERSION, OUTCOME_CONTRACT_VERSION, AGREEMENT_CONTRACT_VERSION, STORE_VERSION, DEFAULT_MODEL, DEFAULT_TOKENIZER, MAX_OBSERVATIONS, MIN_OBSERVATIONS, MAX_SAMPLES, DEFAULT_SAMPLES, MAX_FORECAST_BARS, DEFAULT_TIMEOUT_MS, MAX_QUEUE, MAX_CONCURRENCY, MAX_FORECASTS, MAX_OUTCOMES, MAX_RESPONSE_BYTES, HORIZON_MAPPINGS });
