"use strict";
const crypto = require("crypto");
const { FORECAST_CONTRACT_VERSION, DEFAULT_MODEL, DEFAULT_TOKENIZER, DEFAULT_SAMPLES, MAX_OBSERVATIONS, HORIZON_MAPPINGS } = require("./constants");
const { validateForecastRequest, validateBars } = require("./schema"); const { deriveSignal, agreement } = require("./analytics");
function createKronosShadowService({ enabled = false, client, store, historyLoader, predictionLoader = () => [], now = () => new Date().toISOString() }) {
  const metrics = { attempted: 0, succeeded: 0, failed: 0, totalDurationMs: 0, latestInferenceDurationMs: null, latestFailure: null };
  function legacyFor(ticker, horizon) { const payload = predictionLoader() || {}; return (payload.predictions || []).find((item) => item.ticker === ticker && String(item.timeframe || item.bestTimeframe || horizon) === horizon) || (payload.predictions || []).find((item) => item.ticker === ticker) || null; }
  async function forecast(raw) {
    if (!enabled) throw Object.assign(new Error("Kronos shadow research is disabled."), { code: "feature_disabled" });
    const request = validateForecastRequest(raw), mapping = HORIZON_MAPPINGS[request.horizon], started = Date.now(); metrics.attempted += 1;
    try {
      const historical = await historyLoader(request.ticker, { lookback: MAX_OBSERVATIONS }); const inputCutoff = historical.bars?.at(-1)?.timestamp; const bars = validateBars(historical.bars, { cutoff: inputCutoff }); const sampleCount = request.sampleCount || DEFAULT_SAMPLES;
      const adapter = await client.infer({ contractVersion: FORECAST_CONTRACT_VERSION, ticker: request.ticker, interval: "1d", inputCutoff, observations: bars, forecastObservationCount: mapping.bars, sampleCount }); const createdAt = now(); const signal = deriveSignal({ ticker: request.ticker, horizon: request.horizon, generatedAt: createdAt, samples: adapter.samples, inputLastClose: bars.at(-1).close, dataQuality: historical.dataQuality || "complete" }); const legacy = legacyFor(request.ticker, request.horizon); const comparison = agreement(legacy?.unifiedDirection, signal.direction, legacy?.timeframe || legacy?.bestTimeframe || request.horizon, request.horizon);
      const record = { id: crypto.randomUUID(), contractVersion: FORECAST_CONTRACT_VERSION, ticker: request.ticker, securityName: legacy?.companyName || historical.securityName || null, modelName: adapter.modelName || DEFAULT_MODEL, modelVersion: adapter.modelVersion || "official-checkpoint", tokenizerVersion: adapter.tokenizerVersion || DEFAULT_TOKENIZER, checkpointIdentifier: adapter.checkpoint || DEFAULT_MODEL, createdAt, inputStartAt: bars[0].timestamp, inputEndAt: bars.at(-1).timestamp, inputObservationCount: bars.length, inputInterval: "1d", forecastStartAt: adapter.samples[0][0].timestamp, forecastEndAt: adapter.samples[0].at(-1).timestamp, forecastObservationCount: mapping.bars, forecastHorizon: request.horizon, horizonMapping: mapping.label, source: { historicalDataSource: historical.source, sourceTimestamp: historical.sourceTimestamp, priceTreatment: historical.priceTreatment || "unadjusted OHLCV", dataQualityState: historical.dataQuality || "complete" }, status: "available", rawForecastSamples: adapter.rawSamples, normalizedForecastSamples: adapter.samples, signal, agreement: comparison, legacyPredictionId: legacy?.predictionId || legacy?.id || null, legacyGeneratedAt: legacy?.scannedAt || legacy?.updatedAt || null, productionInfluence: false, inputBars: bars };
      record.executionMode = adapter.executionMode; record.outputNormalization = adapter.outputNormalization;
      await store.addForecast(record); metrics.succeeded += 1; metrics.latestFailure = null; return record;
    } catch (error) { metrics.failed += 1; metrics.latestFailure = String(error.code || "unavailable").slice(0, 80); throw error; }
    finally { const duration = Date.now() - started; metrics.totalDurationMs += duration; metrics.latestInferenceDurationMs = duration; }
  }
  function diagnostics() { const data = store.read(); return { enabled, serviceReachable: enabled && metrics.succeeded > 0, modelLoaded: enabled && metrics.succeeded > 0, modelName: DEFAULT_MODEL, tokenizerVersion: DEFAULT_TOKENIZER, forecastsAttempted: metrics.attempted, forecastsSucceeded: metrics.succeeded, forecastsFailed: metrics.failed, averageInferenceDurationMs: metrics.attempted ? Math.round(metrics.totalDurationMs / metrics.attempted) : null, latestInferenceDurationMs: metrics.latestInferenceDurationMs, latestFailure: metrics.latestFailure, pendingOutcomes: data.forecasts.filter((forecast) => !data.outcomes.some((outcome) => outcome.forecastId === forecast.id)).length, maturedOutcomes: data.outcomes.filter((outcome) => outcome.status === "matured").length, directionHitRate: data.outcomes.some((outcome) => outcome.status === "matured") ? data.outcomes.filter((outcome) => outcome.status === "matured" && outcome.directionCorrect).length / data.outcomes.filter((outcome) => outcome.status === "matured").length : null, returnMeanAbsoluteError: data.outcomes.some((outcome) => outcome.status === "matured") ? data.outcomes.filter((outcome) => outcome.status === "matured").reduce((sum, outcome) => sum + Math.abs(outcome.returnError), 0) / data.outcomes.filter((outcome) => outcome.status === "matured").length : null, sampleSizeWarning: data.outcomes.length < 30, client: client.diagnostics() }; }
  return { forecast, latest: (ticker) => enabled ? store.latest(String(ticker || "").toUpperCase()) : null, diagnostics };
}
module.exports = { createKronosShadowService };
